# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: falseript
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e '
              Pkg.clone("https://github.com/aminya/Deprecations.jl");
              Pkg.clone(pwd()); Pkg.build("FemtoCleaner");
              Pkg.checkout("AbstractTrees");
              import JSON;
              for (pkg, version) in JSON.parse(readstring("dependencies.json"))
                   LibGit2.with(LibGit2.GitRepo, Pkg.dir(pkg)) do deprepo
                       LibGit2.checkout!(deprepo, version)
                   end;
                   Pkg.pin(pkg);
              end;
              Pkg.resolve();
              Pkg.test("FemtoCleaner"; coverage=true)
              '
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("FemtoCleaner")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
